### ISSUE TITLE
Cannot open virtual output

### ISSUE THREAD

**Issue by JacksonGariety** [justinlatimer/node-midi#100]
Using the following example:

``` javascript
var output = new midi.output();
output.openVirtualPort("test!");
output.sendMessage([176,22,1]);
output.closePort();
```

The following is true:

``` javascript
navigator.requestMIDIAccess().then(function (midi) {
    midi.outputs.size === 0 // true
    midi.inputs.size === 1 // true
})
```

It seems the virtual ports always get "filed" as inputs. Why? For my cases I need a virtual output.

**Comment by drewish** [comment]
i'm assuming the first code is in the node app and the second is in a browser? if that's the case then it seems like it's correct. the output of the node app would become the input to the browser.

**Comment by soulfresh** [comment]
I'm actually seeing the same thing as @JacksonGariety when running a single app.

```javascript
midi = require('midi')
input = new midi.input()
output = new midi.output()

logPorts = ->
  console.log '--- IN ---'
  console.log 'port count: ', input.getPortCount()
  for i in [0..input.getPortCount() - 1]
    console.log '>', input.getPortName(i)

  console.log '--- OUT ---'
  console.log 'port count:', output.getPortCount()
  for i in [0..output.getPortCount() - 1]
    console.log '>', output.getPortName(i)

openPort = (name) ->
  for i in [0..input.getPortCount() - 1]
    if input.getPortName(i) is name
      input.openPort(i)


logPorts()
console.log '--------------------------------------'

output.openVirtualPort('TestPort')

logPorts()
console.log '--------------------------------------'
```

The above results in:

```
--- IN ---
port count:  0
--- OUT ---
port count: 0
--------------------------------------
--- IN ---
port count:  1
> TestPort
--- OUT ---
port count: 0
```

Notice that the virtual **output** port I created (TestPort) is listed as an input but not as an output. Is this expected? It confused me for a while but I made the assumption that it's intended to guard against connecting to the virtual port I just opened(?) for some reason.

If @JacksonGariety is using the Chrome MIDI API, I imagine he's trying to create a virtual port with node-mide that he can use to send midi to from his browser since creating virtual ports isn't supported by Chrome at the moment.

**Comment by aolsenjazz** [comment]
To help clarify, output.openVirtualPort(...) is working correctly. Usage of Chrome MIDI API is irrelevant here.

````javascript
const midi = require('midi');

let iWatcher = new midi.Input();
let oWatcher = new midi.Output();

let input = new midi.Input();
input.openVirtualPort('inDummy');
console.log(`Input Ports: ${iWatcher.getPortCount()}\nOutput Ports: ${oWatcher.getPortCount()}\n`);
input.closePort();
````
outputs:
````shell
Input Ports: 0
Output Ports: 1
````
While:
````javascript
let output = new midi.Output();
output.openVirtualPort('outDummy');
console.log(`Input Ports: ${iWatcher.getPortCount()}\nOutput Ports: ${oWatcher.getPortCount()}\n`);
output.closePort();
````
outputs:
````shell
Input Ports: 1
Output Ports: 0
````

As @justinlatimer mentioned (much) earlier, `input.openVirtualPort()` *to other midi clients* is an *output*. Similarly, `output.openVirtualPort()` *to other midi clients* is an *input*.
