### ISSUE TITLE
Read device names

### ISSUE THREAD

**Issue by jsosulski** [justinlatimer/node-midi#102]
Hello,

is there a way to read the midi device name for the midi ports?
For example, I created a virtual output named "Launchpad_output". If i get the names of all available ports in nodejs, I can see the new virtual output as "RtMidi Output Client 128:0". However, when I list my available devices using `aconnect -i` I get the following information:

```
client 128: 'RtMidi Output Client' [type=user]
    0 'Launchpad_output'
```

Can i acces the device name "Launchpad_output" in nodejs?

**Comment by dc-p8** [comment]
Hey, have you solved this problem? Since the issue is closed.... I have the same thing. On Web Midi API, I got the right name, but if I read all names with node-midi, I got "RtMidi Input Client" and "RtMidi Output Client". I also tried some Forks of node-midi but it doesn't change anything.

**Comment by jsosulski** [comment]
Hey, no sorry I did not. As far I remember I also had issues when reconnecting the Launchpad and moved on to try different frameworks (but did not find one that fit my needs).

**Comment by dc-p8** [comment]
Same for me. I looked for some Web Midi API implementation and finally realized that the only viable implémentation is in the browser itself (JZZ implémentation has an issue with virtual ports), so I made my app running on browser...
