### ISSUE TITLE
Virtual ports in Windows systems

### ISSUE THREAD

**Issue by jaycliff** [justinlatimer/node-midi#104]
Is there a way to create virtual midi ports in Windows?

**Comment by Lokua** [comment]
No way to do this natively last time I checked. I've always used [loopmidi](http://www.tobias-erichsen.de/software/loopmidi.html).

**Comment by jaycliff** [comment]
I see :( I've been using loopmidi too. I hope Tobias Erichsen would share his code for the windows implementation...

**Comment by Pomax** [comment]
Is this an issue around needing to compile RtMidi on windows using node-gyp in some fancy way, or does RtMidi compiled for windows not allow for virtual ports, despite itself supposedly working fine on Windows?

**Comment by jaycliff** [comment]
That could possibly be. There may be an issue regarding JACK for Windows.

**Comment by derwaldgeist** [comment]
Any updates on this?

**Comment by safazi** [comment]
bump!

**Comment by neauoire** [comment]
bump

**Comment by DustinJSilk** [comment]
Any update on this? Or, how can i create a virtual midi port using loopMIDI and connect to it with node-midi? It's telling me it can't find a midi output with the requested name.

**Comment by Pomax** [comment]
loopmidi's fairly straight forward; install it, _run it_, and create one or more MIDI devices:

![image](https://user-images.githubusercontent.com/177243/75401755-f0c62b80-58b7-11ea-8267-f75d50de8803.png)

As long as it's running, you'll be able to connect to those named devices. With of course the obvious downside that you have to run it. There's no convenient minimize-to-tray or the like, it's an application that you need to keep open for as long as you need a virtual midi channel.

Then on the "playing actual sound" side of things, you need to have that MIDI device connect to a virtual instrument of some sort (e.g. by using a DAW like [Reaper](http://reaper.fm/) or [Cakewalk](http://www.cakewalk.com/), or some standalone VST or midi-controllable host), and on the programming side you need to tell Node to send MIDI output using that device.

I ended up using https://github.com/dinchak/node-easymidi for that, which is a wrapper around node-midi.

**Comment by DustinJSilk** [comment]
Oh right okay, **thanks**! I didn't realise loopMidi was adding an integer to the end of the device name. Got it working [here](https://github.com/DustinJSilk/picap-remote-midi/commit/4bada0f9b6a6ec0f2b1d6d0fb3b40eb3afe27607) if anyone else ever needs the reference, too.
