### ISSUE TITLE
Could output.sendMessage be aliased to output.send?

### ISSUE THREAD

**Issue by danielksato** [justinlatimer/node-midi#105]
Would it be possible for output.sendMessage to be aliased to output.send? This would be consistent with the Web MIDI API, and would make [MIDIPlayer](https://github.com/nfroidure/MIDIPlayer) more usable on Node.

**Comment by mrmowgli** [comment]
I suspect you could just decorate the output Prototype and then just delegate to the original sendMessage().  If that works you could send a pull request :)

**Comment by justinlatimer** [comment]
Implemented in commit b14a6e3 and published in v1.0.2
