### ISSUE TITLE
Publish an new version with nan module up-to-date

### ISSUE THREAD

**Issue by DjDCH** [justinlatimer/node-midi#110]
Is it possible to publish a new version with the up-to-date nan module? The nan module was update a month ago, but no new version of node-midi was publish to npm.

Not having the latest nan version is preventing users from compiling node-midi on node `6.*`. Three days ago, @thorikawa had the same issue and reported it here #109.

Please consider to bump the nan version to the latest (currently `2.3.5`) and publishing a new version of node-midi.

**Comment by drewish** [comment]
i just published a new 0.9.5 release, please use that.
