### ISSUE TITLE
Cannot reuse input objects

### ISSUE THREAD

**Issue by soulfresh** [justinlatimer/node-midi#112]
I'm not sure if this is intended but using a single input object to open a port, close it and then open another port causes an unrecoverable exception:

``` javascript
midi = require('midi')

input = new midi.input()
for i in [0..4]
  console.log i, '> opening'
  input.openPort(2)
  console.log i, '< closing'
  input.closePort()
  console.log '---------------'
```

results in:

```
0 '> opening'
0 '< closing'
---------------
1 '> opening'
1 '< closing'
Assertion failed: (!(handle->flags & (UV_CLOSING | UV_CLOSED))), function uv_close, file ../deps/uv/src/unix/core.c, line 103.
[1]    4060 abort      ./node_modules/.bin/coffee scripts/portCloseTest.coffee
```

If midi objects should not be reused in this way, I can open a PR with an update to the documentation. However, it might be nice if there was better error messaging around this issue or better yet if it were non-fatal.

**Comment by mrmowgli** [comment]
In your sample code you are opening and closing port two four times, is that what you intended?

Also I suspect it takes time to close and reallocate, perhaps you can try this with a delay after the close? Perhaps with promises?

**Comment by soulfresh** [comment]
Thanks for your reply. In my own application, I was able to work around this issue by making sure I never reused the midi input objects. However, it took me a while to debug this issue so was hoping to get the docs updated (or the underlying issue fixed) so that others won't struggle with the same thing.

**Comment by ahicox** [comment]
for what it's worth, I found the same thing, just rendering a list of midi inputs in a menu. If the user wants to swap midi input ports, you've gotta destroy the input object and re-instantiate. Workaround is good enough. Glad someone posted this, or I'd have been scratching my head for hours :-)
