### ISSUE TITLE
Cannot install midi, build error

### ISSUE THREAD

**Issue by Loxoz** [justinlatimer/node-midi#128]
### That's what happens:
**fatal error LNK1106: invalid file or disk full: cannot search on 0x1E5D34**

```
node -v && npm -v
v8.10.0
5.6.0

Windows 10 x64
```
Some more:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! midi@0.9.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the midi@0.9.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
```
node_modules\nan\nan_maybe_43_inl.h(220): warning C4996: 'v8::Array::CloneElementAt': has been declared deprecated
node_modules\nan\nan_implementation_12_inl.h(40): warning C4996: 'v8::BooleanObject:: New': has been declared deprecated
node_modules\nan\nan.h(1989): warning C4996: 'v8::Object::SetAccessor': has been declared deprecated
```

**Comment by daslicht** [comment]
same her eunder macos mojave
```
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/daslicht/.node_modules/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/Users/daslicht/.node_modules/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/daslicht/DEV/Sound Projects/node-midi/node_modules/midi
gyp ERR! node -v v11.1.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN node-midi@1.0.0 No description
npm WARN node-midi@1.0.0 No repository field.
npm ERR! Darwin 18.2.0
npm ERR! argv "/usr/local/bin/node" "/Users/daslicht/.node_modules/bin/npm" "install"
npm ERR! node v11.1.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE

npm ERR! midi@0.9.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the midi@0.9.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the midi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs midi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls midi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by daslicht** [comment]
https://gist.github.com/daslicht/9cd8a6493c9811b927d7c4aaf48aac39

**Comment by prussian-blue** [comment]
Same under mojave as @daslicht but slightly different

`2796 verbose stack Error: midi@0.9.5 install: `node-gyp rebuild`
2796 verbose stack Exit status 1
2796 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
2796 verbose stack     at EventEmitter.emit (events.js:182:13)
2796 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2796 verbose stack     at ChildProcess.emit (events.js:182:13)
2796 verbose stack     at maybeClose (internal/child_process.js:962:16)
2796 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
2797 verbose pkgid midi@0.9.5`

tried with multiple version of node just in case, but resulting in the same previous log

`  node/8.9.0
  ο node/10.13.0
    node/11.2.0
    node/11.9.0`

**Comment by daslicht** [comment]
Hm :/ hopefully there will be a fix or alternative some day

**Comment by daslicht** [comment]
hm I have python 2.7.10 installed, i think via homebrew. How do you installed it ?

Library/Frameworks/Python.framework/Versions/ shows only version 3 tho

**Comment by prussian-blue** [comment]
I went directly to https://www.python.org/downloads/release/python-2715/ and use their installer.

**Comment by justinlatimer** [comment]
Try again with v1.0.0, reopen if problem still persists.

**Comment by XanderCodes** [comment]
I'm still getting this error after trying @danivicario 's solution (installing python with their installer) with no luck.
