### ISSUE TITLE
npm install fail on windows 7

### ISSUE THREAD

**Issue by jbloit** [justinlatimer/node-midi#134]
Hi,
Trying to install on windows 7, with python 2.7 installed and visual studio express 2013. I get the following error when running npm install midi;

C:\Users\User\Documents\testMIDI>npm install midi

> midi@0.9.5 install C:\Users\User\Documents\testMIDI\node_modules\midi
> node-gyp rebuild

C:\Users\User\Documents\testMIDI\node_modules\midi>if not defined npm_config_nod
e_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle
\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (nod
e "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.j
s" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  node-midi.cpp
  win_delay_load_hook.cc
c:\users\user\.node-gyp\10.15.3\include\node\v8.h(2570): error C2144: syntax er
ror : 'int' should be preceded by ';' (..\src\node-midi.cpp) [C:\Users\User\Doc
uments\testMIDI\node_modules\midi\build\midi.vcxproj]
c:\users\user\.node-gyp\10.15.3\include\node\v8.h(2570): error C4430: missing t
ype specifier - int assumed. Note: C++ does not support default-int (..\src\nod
e-midi.cpp) [C:\Users\User\Documents\testMIDI\node_modules\midi\build\midi.vcxp
roj]
c:\users\user\.node-gyp\10.15.3\include\node\v8.h(4273): error C2610: 'v8::Wasm
CompiledModule::TransferrableModule::TransferrableModule(v8::WasmCompiledModule
::TransferrableModule &&)' : is not a special member function which can be defa
ulted (..\src\node-midi.cpp) [C:\Users\User\Documents\testMIDI\node_modules\mid
i\build\midi.vcxproj]
c:\users\user\.node-gyp\10.15.3\include\node\v8.h(4276): error C2610: 'v8::Wasm
CompiledModule::TransferrableModule &v8::WasmCompiledModule::TransferrableModul
e::operator =(v8::WasmCompiledModule::TransferrableModule &&)' : is not a speci
al member function which can be defaulted (..\src\node-midi.cpp) [C:\Users\User
\Documents\testMIDI\node_modules\midi\build\midi.vcxproj]
c:\users\user\.node-gyp\10.15.3\include\node\v8.h(4362): error C2610: 'v8::Wasm
ModuleObjectBuilderStreaming::WasmModuleObjectBuilderStreaming(v8::WasmModuleOb
jectBuilderStreaming &&)' : is not a special member function which can be defau
lted (..\src\node-midi.cpp) [C:\Users\User\Documents\testMIDI\node_modules\midi
\build\midi.vcxproj]
c:\users\user\.node-gyp\10.15.3\include\node\v8.h(4367): error C2610: 'v8::Wasm
ModuleObjectBuilderStreaming &v8::WasmModuleObjectBuilderStreaming::operator =(
v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function wh
ich can be defaulted (..\src\node-midi.cpp) [C:\Users\User\Documents\testMIDI\n
ode_modules\midi\build\midi.vcxproj]
c:\users\user\.node-gyp\10.15.3\include\node\v8.h(4632): error C2146: syntax er
ror : missing ';' before identifier 'size_t' (..\src\node-midi.cpp) [C:\Users\U
ser\Documents\testMIDI\node_modules\midi\build\midi.vcxproj]
c:\users\user\.node-gyp\10.15.3\include\node\v8.h(4632): error C4430: missing t
ype specifier - int assumed. Note: C++ does not support default-int (..\src\nod
e-midi.cpp) [C:\Users\User\Documents\testMIDI\node_modules\midi\build\midi.vcxp
roj]
C:\Users\User\.node-gyp\10.15.3\include\node\node_buffer.h(36): error C2597: il
legal reference to non-static member 'v8::TypedArray::kMaxLength' (..\src\node-
midi.cpp) [C:\Users\User\Documents\testMIDI\node_modules\midi\build\midi.vcxpro
j]
C:\Users\User\.node-gyp\10.15.3\include\node\node_buffer.h(36): error C2440: 'i
nitializing' : cannot convert from 'unknown' to 'const unsigned int' (..\src\no
de-midi.cpp) [C:\Users\User\Documents\testMIDI\node_modules\midi\build\midi.vcx
proj]
          There is no context in which this conversion is possible
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:248:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\User\Documents\testMIDI\node_modules\midi
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN testmidi@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! midi@0.9.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the midi@0.9.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2019-04-15T17_16_41_3
05Z-debug.log

C:\Users\User\Documents\testMIDI>

does that sound familiar?

**Comment by justinlatimer** [comment]
Try again with v1.0.0, reopen if problem still persists.
