### ISSUE TITLE
Install failed on node 12

### ISSUE THREAD

**Issue by marksyzm** [justinlatimer/node-midi#136]
It's a new V8 engine and too many errors are coming up for this now. Is this repo now abandonware? I've noticed there's not been any updates for quite a while

**Comment by cleverplatypus** [comment]
Yep, trying to use midi in a fresh Electron 5 app. v8 12 finally got rid of deprecated V8::Handle which causes compilation to fail.

https://electronjs.org/blog/nodejs-native-addons-and-electron-5

Anyone going to fork or authors going to refactor this?

**Comment by marksyzm** [comment]
If that's all it is then I'd be happy to do it if it got merged.

**Comment by cleverplatypus** [comment]
> If that's all it is then I'd be happy to do it if it got merged.

@marksyzm that would be amazing. Not sure if the author is still alive and kicking and how long the merge would take.

Anyhow, I made a couple of attempts to refactor the code as suggested by some forums but I still get  API incopatibility errors why I try to `yarn add midi` from my fork. My C is rather rusty and I'm not sure what I'm doing in there anyway 🤣 

Here's one of the posts I found re the topic:
https://github.com/bcoin-org/bcrypto/issues/7

**Comment by justinlatimer** [comment]
I'm alive - I've been out of the js scene for quite a few years. I'll try and pick this module back up and see what I can do.

**Comment by marksyzm** [comment]
Excellent 🙂 I'm looking to try and get the virtual ports working on
windows too via the loopmidi SDK if you're interested?
-- 
Mark Elphinstone-Hoadley
www.oxfordsourceltd.com

**Comment by stevenleeg** [comment]
Also running into this issue on MacOS and node 12.3.1. Glad to see you're still around @justinlatimer <3

**Comment by justinlatimer** [comment]
v1.0.0 containing this fix published to npm.
