### ISSUE TITLE
Delay resolving promise - event loop issue?

### ISSUE THREAD

**Issue by Malvineous** [justinlatimer/node-midi#157]
If I try to resolve a `Promise` inside the input's `message` event handler, the promise doesn't get resolved until eight seconds later.  Is the C++ event handling code not interfacing with Node correctly?

Here is some code that will reproduce the problem under Linux:

```
const midi = require('midi');

let resolvePendingPromise;
const promise = new Promise((resolve, reject) => {
	resolvePendingPromise = resolve;
});

const input = new midi.Input();
input.on('message', (deltaTime, message) => {
	resolvePendingPromise(message);
});
input.openPort(0);

async function run()
{
	const output = new midi.Output();
	output.openPort(0);
	console.log('Sending message');
	output.sendMessage([176, 22, 1]);
	console.log('Message sent');
	output.closePort();

	// Uncomment this line to remove the delay.
	//setImmediate(() => {});

	console.log('Waiting for result');
	const result = await promise;
	console.log('Got result', result);

	input.closePort();
}

run();
```

When you run it, the `await` will block for eight seconds, and the `Got result` line will appear after the delay.  By uncommenting the `setImmediate` call, there is no delay.

This seems to me like the library is not allowing Node's event loop to operate normally.

**Comment by RoL0NL** [comment]
I still experience a random delay when using a http.request inside an intput.on('message'....

Minimum working example:
```

const midiLib = require('easymidi');
const http = require('http');

const input = new midiLib.Input('mididevice');

input.on('message', (deltaTime, message) => {
  var req = http.request('http://127.0.0.1:8080/api/');
  req.end();
  console.log('Event!');
});
```

Console shows 'Event!' immediate, http request has a delay between 0-10 seconds.
