### ISSUE TITLE
Error macOS initialization error -50

### ISSUE THREAD

**Issue by tschiemer** [justinlatimer/node-midi#168]
Message from nodejs looks as follows:

> MidiInCore::initialize: error creating OS-X MIDI client object (-50).

Can (possibly) randomly occur - depends on when/if RtMidi objects are deleted using the object destructors which is decided by the nodejs garbage collector.

Reproduce by running `node --expose-gc XY.js` of (no other macOS MIDI Clients active):

```js
const midi = require('midi');

var i = 0;

// Close the port when done.
setInterval(function() {
  console.log(`Round ${++i}`);

  global.gc();

  var input = new midi.Input();

  delete input;

}, 1000);
```

Documented for informational purposes, underlying RtMidi problem on macOS systems, likely to be fixed in the future:

https://github.com/thestk/rtmidi/issues/155

**Comment by justinlatimer** [comment]
Updated RtMidi in 7c659437963c311bc62d94898ad8867e220a8899, published to npm in `v2.0.0`
