### ISSUE TITLE
Cannot use with webpack

### ISSUE THREAD

**Issue by Zagorodnyi** [justinlatimer/node-midi#180]
Is it even possible to webpack this library? I'm getting this error with my react app:

TypeError: Error.captureStackTrace is not a function. (In 'Error.captureStackTrace(dummy)', 'Error.captureStackTrace' is undefined)

**Comment by sploders101** [comment]
I don't believe it is. This is a native module providing bindings to rtMidi from Node.JS, and is compiled into a binary format to allow interoperability with C++. Webpack only deals in javascript, but native modules are binaries that specify a javascript API. They are not javascript.
