### ISSUE TITLE
hello impossible to build with node-gyp

### ISSUE THREAD

**Issue by DiegoRamirez90** [justinlatimer/node-midi#194]
hello it's been two days since i try to build the midi package but i can't.

Thank you in advance for your assistance

here is the error i get:

`D:\electron\launchpad>npm install midi

> midi@1.0.3 install D:\electron\launchpad\node_modules\midi
> node-gyp rebuild

D:\electron\launchpad\node_modules\midi>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Shadow\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn D:\Program Files (x86)\Microsoft Visual Studio\2019\Community" ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Shadow\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\electron\launchpad\node_modules\midi
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v8.0.0
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
npm WARN launchpad@1.0.0 No description
npm WARN launchpad@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! midi@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the midi@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shadow\AppData\Roaming\npm-cache\_logs\2021-04-24T14_28_13_656Z-debug.log`

and here is the log file : https://pastebin.com/cP5xxPQb

**Comment by justinlatimer** [comment]
Looks like you don't have Visual Studio installed or the installation is corrupted.
