### ISSUE TITLE
Fails to Install on Apple Silicon M1 Macs

### ISSUE THREAD

**Issue by chrisspiegl** [justinlatimer/node-midi#215]
Hello, I just tried using one of my projects which includes easymidi and by extension node-midi on my new M1 MacBook and it fails to install.

I was able to narrow it down to the dependency on `opencv4nodejs-prebuilt` and was wondering if it may be possible to work around this issue? Possibly work with an alternative library?

I also requested support for M1 on the `opencv4nodejs-prebuilt` repository: https://github.com/nut-tree/opencv4nodejs/issues/14

Any help would be appreciated.

I am trying to not have to run Node.JS inside a Rosetta Container and get this project up and running natively.

Looking forward to hopefully finding a solution together.

**Comment by chrisspiegl** [comment]
Sorry, I put in some further investigation and found out that this was not at all the fault of this package but a different dependency. If I could I would delete this issue but since that's impossible… I'll be closing it.

**Comment by alana314** [comment]
I had a world of pain getting this installed and working with electron, so I wanted to share what finally worked (and stopped the NODE_MODULE_VERSION and mach-o x64 errors):  
```
npm install midi --build-from-source --target_arch=arm64 --fallback-to-build
npm install --save-dev @electron/rebuild
./node_modules/.bin/electron-rebuild -f --arch=arm64
```

**Comment by Julusian** [comment]
This project looks to not be maintained anymore. Instead you can use my fork [@julusian/midi](https://github.com/julusian/node-midi). It includes prebuilt binaries for common platforms, avoiding the need to compile it locally in almost all cases.
See https://github.com/justinlatimer/node-midi/pull/228 for more details on the changes.

**Comment by alana314** [comment]
@Julusian thanks! I did still have to ./node_modules/.bin/electron-rebuild -f --arch=arm64 with your package or it would by default try and use a mach-o x86 build.

**Comment by Julusian** [comment]
Oh right yeah. I forgot that https://github.com/electron/rebuild/issues/1055 is still an 'issue'.
It shouldn't need to rebuild it, but electron-rebuild isnt smart enough to realise that, so it does it anyway and I guess sometimes gets it wrong?

In my electron projects I don't have any dependencies which need rebuilding, so I have turned rebuilding off to avoid these issues
