### ISSUE TITLE
Delta time

### ISSUE THREAD

**Issue by PerryRylance** [justinlatimer/node-midi#238]
Hi folks, I have tried plugging this into `@perry-rylance/midi` without success.

The module doesn't expect messages greater than three bytes in length. My note on events are four bytes long, the first byte is the delta time.

Based off of this I assume that this library isn't designed to work with delta times?

**Comment by jwetzell** [comment]
Standard MIDI 1.0 messages have a max length of 3 bytes. MIDI messages don't contain the delta time so the remaining 3 bytes would be used to construct the MIDI message.

**Comment by PerryRylance** [comment]
Thank you. None of the specs I consulted were clear about this!
