### ISSUE TITLE
problem installing module

### ISSUE THREAD

**Issue by ghost** [justinlatimer/node-midi#25]
(previously added to issue #16 moved to here)
Failure installing the module on the following environment:

OSX10.7.5, latest xcode
node & npm installed via mac ports (node: v0.10.12/npm: 1.2.30)

i.e. this is a new environment, macports just grabbed the latest versions avail

npm is fetching midi 0.7.0 from the repo

When I do 'npm install midi' - this is what I get, immediately after the node-gyp rebuild:

```
CXX(target) Release/obj.target/midi/src/node-midi.o
In file included from ../src/node-midi.cpp:8:
../src/lib/RtMidi/RtMidi.cpp:473:26: warning: implicit conversion of NULL
constant to 'MIDIEntityRef' (aka 'unsigned int') [-Wnull-conversion]
MIDIEntityRef entity = NULL;
~~~~~~ ^~~~
0
```

& the module is not built, so 'require('midi')' fails.

update: checking on a macbook with known working midi 0.7.0: same config (Lion 10.7.5, node/npm via macPorts).
With node = 0.10.10 & npm = 1.2.28. node midi seems to work fine.

In order to preserve your working version when updating packages via MacPorts you can exclude node & npm by using something like:

'sudo port upgrade outdated and not nodejs or npm'

A

**Comment by jcpsimmons** [comment]
I'm having the same issue.

**Comment by drewish** [comment]
@jcpsimmons are you sure you're having the same issue? You trying to use the old version? If not open up a new issue and include the errors you're encountering.
