### ISSUE TITLE
Crash when instantiating multiple midi input instances

### ISSUE THREAD

**Issue by soulfresh** [justinlatimer/node-midi#58]
To start, thank you for this amazing software. It's been incredibly useful. 

We've been experiencing crashes using this package on OSX (may not be OSX specific). This occurs when we instantiate two midi.input objects and then only use one of them. I'm not sure if this is expected functionality but since it's not documented, I assume it's not. 

We put together a small test to demonstrate the crashes here (steps to reproduce are at the bottom):
https://github.com/OSCModulator/midi-test/blob/master/midi-test.coffee

Test 2 seems to crash somewhere around 382 messages.

We'd love your thoughts on this. For the moment we plan to work around the issue.

Thanks again for this great tool!

**Comment by soulfresh** [comment]
This issue appears to be fixed in 0.9.2 so I'll close this ticket.

**Comment by drewish** [comment]
Great, glad to hear that.
