### ISSUE TITLE
Can not build or run with node v0.12.0 on OS X

### ISSUE THREAD

**Issue by boristian** [justinlatimer/node-midi#61]
Hello,
i can not build or run the node module with node.js v0.12.0 on OS X Mavericks. It seems to be a problem with the new v8 version, node v0.12.0 uses.
When i'm trying to install it with
```
npm install midi
```
i get lots of errors and
```
Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
```
Whe i use a prebuild module, i get
```
Error: Module did not self-register.
```
Greets and thanks in advance,
Christian

**Comment by justinlatimer** [comment]
PR #52 includes changes to use NAN to handle this. If you checkout that branch from @drewish's fork you should be able to test that. The error messages you're receiving might help as well. 

Now that node v0.12.0 is out I should def get around to merging that.

**Comment by drewish** [comment]
I'll just go ahead and merge it. I think I was just waiting to see if any bugs came up with it.

**Comment by drewish** [comment]
I had to upgrade NaN and make a couple of tweaks to ensure it still compiled against 0.10.x but I think it should be good to go. 

@boristian could you try the code in master and let me know how it goes? If this looks good we can tag it and get a new release out.

**Comment by boristian** [comment]
It's working, great. Thank you.
