### ISSUE TITLE
npm install fails when VS2015 RC is installed

### ISSUE THREAD

**Issue by SBRK** [justinlatimer/node-midi#69]
It seems that the midi module can't be installed when Visual Studio 2015 RC is installed.
I can't recall the exact error but it was on node-midi.cpp I think.
I uninstalled VS2015 and reinstalled VS2013 and it worked fine after that

**Comment by drewish** [comment]
If anyone else gets the exact error please post a comment with it.

**Comment by drewish** [comment]
Closing due to lack of feedback.

**Comment by lpeachl** [comment]
VS2015 compile failed with this error
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified.

**Comment by lpeachl** [comment]
It seem VS2015 doesn't install C++ by default. i tried reinstall vc++ and compile went successfully.
