### ISSUE TITLE
Support for JACK Audio Connection Kit

### ISSUE THREAD

**Issue by egasimus** [justinlatimer/node-midi#70]
It seems that replacing `__LINUX_ALSA__` with `__UNIX_JACK__` and `-lasound` with `-ljack` in `binding.gyp` allows RtMidi to use JACK instead of ALSA for MIDI. However, adding both side-by-side seems to compile the library with just ALSA support. Is it possible to have both enabled, or to be able to choose which one to use?

**Comment by justinlatimer** [comment]
Looks like this is supported by the underlying MIDI library used, RtMidi - [see here for details on how to support multiple APIs](http://www.music.mcgill.ca/~gary/rtmidi/#multi)

It'd mean some code changes on our side. A pull request implementing that would be welcomed :wink:

Thanks!
