### ISSUE TITLE
Compatible with OSS / Alsa

### ISSUE THREAD

**Issue by fulldecent** [justinlatimer/node-midi#72]
When running on Mac, Is this compatible with the device files that OSS / Alsa use on Linux.

In other words, I use Mac / Gimp which has "Midi input" which really expecting OSS or Alsa. Will this program allow creating a special file / FIFO which works with that?

**Comment by drewish** [comment]
On Mac it uses CoreAudio, you might be able to get it to build against ALSA but I'm not sure if the device files would follow the same format. Might be worth installing VirtualBox and setting up Linux to test it out.
