### ISSUE TITLE
closed virtual ports still "hang around"

### ISSUE THREAD

**Issue by szymonkaliski** [justinlatimer/node-midi#75]
If I do this:

```javascript
var output;

function newOutput(name) {
  if (output) { output.closePort(); }

  output = new midi.output();
  output.openVirtualPort(name);
}

newOutput("test-1");
newOutput("test-2");
newOutput("test-3");
```

I would like to see only "test-3" in Max/MSP, Ableton, etc... but I get all of the outputs (with test-1 and test-2) even thought I closed them. Is there something I can do to "clean" those up?

**Comment by drewish** [comment]
What plantform are you on?

**Comment by szymonkaliski** [comment]
Mac OSX 10.10.4

**Comment by szymonkaliski** [comment]
Any news on this? I re-open ports frequently in the app I'm making and those "dangling" ones are very ugly...

**Comment by drewish** [comment]
Can you see the hanging ports from within this module? Or an app that ships with OS X that can demonstrate the issue?

**Comment by szymonkaliski** [comment]
Hey @drewish thanks for responding, I'm on holidays and will answer you in ~week.

**Comment by szymonkaliski** [comment]
```javascript
var midi = require('midi');
var output;

[ 'a', 'b', 'c', 'd' ].forEach(function(portName) {
  if (output) {
    output.closePort();
  }

  output = new midi.output();
  output.openVirtualPort(portName);
});

var input = new midi.input();

console.log('ports: ' + input.getPortCount());

for (var i = 0; i < input.getPortCount(); ++i) {
  console.log('port [' + i + ']: ' + input.getPortName(i));
}
```

As far as I understand only port `d` should be open, but running this I get:

```
ports: 4
port [0]: a
port [1]: b
port [2]: c
port [3]: d
```

**Comment by szymonkaliski** [comment]
Hey again, @drewish does it work the same way for you? Do you have any idea where should we poke to look for this error?

**Comment by szymonkaliski** [comment]
sorry for bumping @drewish, but I still have this issues, any news on that?

**Comment by justinlatimer** [comment]
Looks like this is a problem with the underlying RtMidi library we use - if you look at the [source for ``closePort``](https://github.com/thestk/rtmidi/blob/master/RtMidi.cpp#L961) it calls ``MIDIPortDispose()`` - but I think this should be [MIDIEndpointDispose](https://developer.apple.com/library/mac/documentation/MusicAudio/Reference/CACoreMIDIRef/MIDIServices/CompositePage.html#//apple_ref/c/func/MIDIEndpointDispose) if the port is virtual and I'm reading the Apple docs correctly.

**Comment by szymonkaliski** [comment]
Thanks for pointing me in this direction, I'll try patching it and I'll see if it helps.
If you have any other pointers — let me know! I'd love to have it solved.

**Comment by szymonkaliski** [comment]
@justinlatimer thanks! it worked! :) PR submitted!

**Comment by noerw** [comment]
can confirm this on Ubuntu 14

**Comment by szymonkaliski** [comment]
@noerw you're probably using alsa, so my fix: https://github.com/justinlatimer/node-midi/pull/91 probably will not work, but maybe you could poke around in rtmidi and try something similar for your audio backend?

**Comment by noerw** [comment]
sorry, my mistake. this seems to be a different thing/bug:

ALSA creates a virtual midi IO loop by default, but these ports are not listed if one iterates over the available ports, like [here](https://github.com/noerw/node-midisrv/blob/7f0d41bb89a77004bafa1c946f946060aeca2d71/midisrv.js#L24-L31).

When i create a virtual port by myself using `input.openVirtualPort("test-in")`, both the default ALSA port, as well as my created port are listed.
I thought, the second one was still left from an old instance..

**Comment by szymonkaliski** [comment]
Hm, yeah, seems like a different issue :)

**Comment by drewish** [comment]
Can we close this now?

**Comment by szymonkaliski** [comment]
Yeah!
