### ISSUE TITLE
io.js 3.0 and raspberry pi using debian fails

### ISSUE THREAD

**Issue by mrmowgli** [justinlatimer/node-midi#78]
Seems to completely crash and burn, mostly in the nan sub-package.  Anyone else got this running or is this stable on some other version of io.js?

Using straight from git, Alsa has been installed (asoundlib2-dev), python 2.7 exists, and node-gyp is installed.  Alsa utils and alsa-oss are installed and working.

kernel: Linux marjipoor 3.18.11+ #781 PREEMPT Tue Apr 21 18:02:18 BST 2015 armv6l GNU/Linux
gcc version: gcc (Debian 4.6.3-14+rpi1) 4.6.3
g++ version: g++ (Debian 4.6.3-14+rpi1) 4.6.3

Here's the error:  http://pastebin.com/g8sL5qcw

**Comment by mrmowgli** [comment]
Ah looks like a duplicate of this: 
https://github.com/justinlatimer/node-midi/pull/76#issuecomment-132069817

**Comment by drewish** [comment]
What version of g++ do you have installed? io.js 3 seems to require g++-4.8.

**Comment by mrmowgli** [comment]
Hrm, g++ version is 4.6.3, that's the latest built in to Raspberry Pi with the Debian  distro.  I'll try downgrading to io.js 2 and see if that works.

**Comment by mrmowgli** [comment]
Hrmm, downgrading to io.js 2.5.0 worked fine.  So this is really an issue with the current debian repo and g++ in relation to io.js.  Closing.
