### ISSUE TITLE
tmux - Couldn't connect to com.apple.midiserver

### ISSUE THREAD

**Issue by davydka** [justinlatimer/node-midi#82]
So I was doing a little development in a tmux session and I ran into the error below. If I leave tmux and enter a normal terminal session, everything works as normal. I suppose that this is because tmux is using a client server model and connects over a socket. Any thoughts?

```
2015-09-16 12:52:43.050 node[9837:95015] 12:52:43.050 ERROR:     MIDIClientLib.cpp:199: Initialize: Couldn't connect to com.apple.midiserver; CoreMIDI will not be usable

MidiInCore::initialize: error creating OS-X MIDI client object.

libc++abi.dylib: terminating with uncaught exception of type RtMidiError
```

**Comment by justinlatimer** [comment]
Reading [this StackOverflow post](http://stackoverflow.com/questions/32240058/couldnt-connect-to-com-apple-midiserver), CoreMIDI is only available to a user with a desktop session and this is a limitation of Mac OS X and not related to node-midi.

Thanks!
