### ISSUE TITLE
Compile fails for node v0.11.14 on Ubuntu 14.04

### ISSUE THREAD

**Issue by mrmowgli** [justinlatimer/node-midi#83]
Installing from NPM, crashes on installation, apparently in the NAN code.  Is node-midi on NPM stale?

Alsa has been installed (asoundlib2-dev), python 2.7 exists, and node-gyp is installed. Alsa utils and alsa-oss are installed and working.

kernel: Linux 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

gcc version: gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
g++ version: g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

Here's the error:  http://pastebin.com/eZMAPEjr

**Comment by mrmowgli** [comment]
Works fine with later versions of Node.

**Comment by drewish** [comment]
Yeah we don't test it on that version since it wasn't one of the stable branches. I'd suggest using 0.12.x.

**Comment by drewish** [comment]
I don't think NAN supports that version based on this bit of the read me:
> macro and utility goodness for making add-on development for Node.js easier across versions 0.8, 0.10 and 0.12 as well as io.js.

So I don't think this is something we can address.
