### ISSUE TITLE
Midi Show Control Caveats?

### ISSUE THREAD

**Issue by benwilhelm** [justinlatimer/node-midi#86]
I'm writing a wrapper for your module which will provide an interface for sending and receiving [Midi Show Control][msc], a particular flavor of MIDI used for controlling theatrical devices (lights, sound, video, etc). All of the documentation here shows your module sending and receiving 3-byte messages. Is there anything to prevent me from working with longer sysex messages?  Any other caveats or useful bits of knowledge you'd like to share before I start down this road?

Thanks!

[msc]: http://oktopus.hu/uploaded/Tudastar/MIDI%20Show%20Control%20Specification.pdf

**Comment by drewish** [comment]
I haven't used any of that functionality myself, but we just wrap the rtmidi library so I'd check their docs.

**Comment by benwilhelm** [comment]
will do. Thanks!

**Comment by kj800x** [comment]
@benwilhelm Did you ever discover anything useful about sending/receiving longer sysex messages?

I'm trying to write a node driver for the Behringer X-Touch control surface in XCTL mode, but I can't seem to get the required handshake to work (which should just involve sending `[0x00, 0xF0, 0x00, 0x00, 0x66, 0x14, 0x00, 0xF7]`).

Right now I'd like to confirm that the message is getting sent properly, but I'm not sure that this library supports sysex the way I need it to. If you had any luck with this, maybe we can update the README with an example?
