### ISSUE TITLE
Constructor functions should start with a capital letter.

### ISSUE THREAD

**Issue by knpwrs** [justinlatimer/node-midi#87]
As per JavaScript conventions, constructor functions should start with a capital letter to distinguish them from normal functions. I was going to submit a pull request which would change the logic to the following:

``` js
function input() {
  if (!(this instanceof input)) {
    return new input(...arguments);
  }
  // rest of constructor logic
}
```

This allows constructor calls of `input()` as well as `new input()`, preserving backwards compatibility. I'm not sure how to do this in C++ though. Thoughts?

**Comment by drewish** [comment]
humm... i'd google around a bit i'm sure someone's got an example of how to do it with NAN.

**Comment by KenPowers** [comment]
I think my main issue is that I haven't really done C++ since college. :stuck_out_tongue_winking_eye: 

I'll take a look around and see what I can find.

**Comment by KenPowers** [comment]
I found an example, currently trying to apply it to this library: https://github.com/nodejs/node-addon-examples/blob/6a51626da3438a59d31d43229cee3e6fd09ec8a5/6_object_wrap/nan/myobject.cc#L28-L42
