### ISSUE TITLE
Error when opening output port

### ISSUE THREAD

**Issue by n9** [justinlatimer/node-midi#88]
I am getting the following error message:
`MidiOutWinMM::openPort: error creating Windows MM MIDI output port.`

I am trying to open `Microsoft GS Wavetable Synth` on Windows 10.

(After some investigation I have found the following: http://stackoverflow.com/a/32553208. Not sure whether it is useful here.)

**Comment by iSchluff** [comment]
Same here. But I think it's just an error in the portNumber calculation. I get 2 Output Ports when I have only one Midi Output connected. I can't list the Second one and I can't connect to the first one. Connecting to the Second one however works.

**Comment by justinlatimer** [comment]
Don't have a Windows machine to develop / test on. That link looks useful. Pull requests welcome!

**Comment by nroadley** [comment]
I tested this on a Windows 8.1 machine, which still gives me the same error. However, it only occurs when I try to open a second port to send to the `Microsoft GS Wavetable Synth`. Works fine on osx.

**Comment by MegaMech** [comment]
Any idea how to make this work in node?

[code]
input.on('message', function(deltaTime, message) {
    console.log('m:' + message + ' d:' + deltaTime);
});
 
// Create a virtual input port.
//midi.input.openVirtualPort("Kawa In");
 
// A midi device "Test Input" is now available for other
// software to send messages to.
 
// ... receive MIDI messages ...
 
// Close the port when done.
//midi.closePort();

output.openVirtualPort("t");
if (keypress == 66) {
	output.sendMessage([66,0,0]);
}

output.closePort();

}
[/code]

**Comment by Bholtland** [comment]
Same here. Hoping for a fix :(

**Comment by bloublou2014** [comment]
This is a limitation of the underlying lib RtMidi under windows to create virtual midi port: 

https://ccrma.stanford.edu/~emgraber/256a/final/rtmidi/RtMidi.cpp

This issue can be closed, it's not a node-midi error.

**Comment by wolfy01** [comment]
> This is a limitation of the underlying lib RtMidi under windows to create virtual midi port:
> 
> [ccrma.stanford.edu/~emgraber/256a/final/rtmidi/RtMidi.cpp](https://ccrma.stanford.edu/~emgraber/256a/final/rtmidi/RtMidi.cpp)
> 
> This issue can be closed, it's not a node-midi error.

Limitation. Well, there still isn't a solution to resolve the issue, node-midi or not.
