### ISSUE TITLE
Can not start script on RaspberryPie

### ISSUE THREAD

**Issue by boristian** [justinlatimer/node-midi#89]
Hi,

I'm using node-midi on a Raspberry with Archlinux and Node v5.1.0 Installation is ok, but when I try to start my script, I get:

```
  throw err
  ^

Error: Could not locate the bindings file. Tried:
```
I think I've installed all alsa dependencies. What can be wrong?

Greetz and thanks in advance

**Comment by drewish** [comment]
Huh... do you get any errors when running npm install?

**Comment by boristian** [comment]
Not really, installation was ok. I can try it again and save the output.
Am I missing packages on the system? I've installed alsa-lib, alsa-tools and alsa-utils. Is node v5.1.0 the problem? I had running the script under node v.0.12, so ...

**Comment by drewish** [comment]
I just added node 5.1 to the list of builds Travis tries... it seems to compile correctly there... That error is coming from the bindings module that we use to do the loading: https://github.com/TooTallNate/node-bindings/blob/master/bindings.js#L88-L89

**Comment by mrmowgli** [comment]
I know for me getting this working on the Raspberry Pi, I had to downgrade the version of iojs I was using, because I was running into issues generating the gyp bindings.  

You did install node-gyp globally?

**Comment by grav** [comment]
I get this when trying to install on a Raspberry Pi 1 with Jessie:

```
$ npm install midi
/
> midi@0.9.4 install /home/pi/midi-fun/node_modules/midi
> node-gyp rebuild

make: Entering directory '/home/pi/midi-fun/node_modules/midi/build'
  CXX(target) Release/obj.target/midi/src/node-midi.o
In file included from ../src/node-midi.cpp:1:0:
../node_modules/nan/nan.h:316:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
midi.target.mk:84: recipe for target 'Release/obj.target/midi/src/node-midi.o' failed
make: *** [Release/obj.target/midi/src/node-midi.o] Error 1
```

**Comment by justinlatimer** [comment]
That's a error from inside the NAN module, not midi. Looks like an incompatible node version. What version of node are you using?

-----Original Message-----

**Comment by grav** [comment]
```
$ node --version
v0.10.29
```
It's the one that came with Raspbian Jessie.

I'm not totally sure as to how to use another version of node. I saw in another issue that using iojs 2.5.0 worked on a Pi, but it seems any iojs or node custom install I use, somehow uses the built-in node-gyp.

**Comment by grav** [comment]
With Raspbian Jessie (current latest Raspbian), this is what I needed to get it working
```
 # remove the pre-installed node in order not to conflict
sudo apt-get remove nodejs

# fetch deb and install newer node (v4.2.1)
wget http://node-arm.herokuapp.com/node_latest_armhf.deb 
sudo dpkg -i node_latest_armhf.deb
npm install midi
```
The examples on the frontpage work fine, and new midi devices are recognized as they're plugged in.

**Comment by dm-cracked-sean-knight** [comment]
I was able to get it working on a RPi3.

I installed the repo for Node 6 with this command (change 6 to a 4 if you want):
`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -`

Then I installed these packages:
`sudo apt-get install build-essential nodejs libasound2-dev`

After than any packages I was using that required the midi package started working.

**Comment by drewish** [comment]
Sounds like there's a clear way to do this so I'm going to close the issue.
