### ISSUE TITLE
Web MIDI shim

### ISSUE THREAD

**Issue by grav** [justinlatimer/node-midi#92]
Has there been any attempts to use this project to create a Web MIDI shim (`navigator.requestMIDIAccess()` etc)?

**Comment by grav** [comment]
I guess it would require some kind of runloop, since the web midi api allows you to send a message at a certain time.

**Comment by grav** [comment]
I did a first take on it:
https://www.npmjs.com/package/webmidi-shim
https://github.com/grav/node-webmidi-shim

It's kind of crude, but it allows me to do a sequencer that will both work in Chrome and on my RPi using nodejs (minus the html ;-)

**Comment by drewish** [comment]
Oh cool glad to hear you were able to get something working. I think others will find that useful.
