### ISSUE TITLE
Documentation on output.sendMessage() could be more descriptive

### ISSUE THREAD

**Issue by hjek** [justinlatimer/node-midi#93]
Hi,
Nice project! Just works!

Can I suggest adding to the documentation of output.sendMessage() what the parameters are?

The Readme currently says:

```
// Send a MIDI message. 
output.sendMessage([176,22,1]);
```

Could it be slightly more specific, like:

```
// Send a MIDI message,
output.sendMessage([144,69,127]);
// this sends a midi message with status code 144 which means "Note on" on "Channel 1". (For list of midi status codes, see http://www.midi.org/techspecs/midimessages.php ), and the note 69 ( must be in range 0 - 127, where 69 is 440-Hz concert A) and velocity 127 ( must also be in range 0 - 127 )
```

I had to dig for this information elsewhere, so it would be really handy to just have in the docs.

**Comment by justinjmoses** [comment]
Appreciate you calling this out @hjek - v useful

**Comment by suparngp** [comment]
Found this page which explains why 144 is a Note on on channel 1. 

http://computermusicresource.com/MIDI.Commands.html
