### ISSUE TITLE
Adding timestamp to midi output messages

### ISSUE THREAD

**Issue by grav** [justinlatimer/node-midi#94]
It seems ALSA supports a timestamp on midi notes (http://www.alsa-project.org/alsa-doc/alsa-lib/seq.html - search for "timestamp"), but node-midi doesn't seem to.

Would it be possible to add this to node-midi's API?

**Comment by drewish** [comment]
We wrap the rtmidi library. Do they surface it from ALSA?

**Comment by grav** [comment]
Hm, doesn't seem like it. I'm closing the issue.

**Comment by grav** [comment]
Actually, it's more a matter of sending the timestamp to ALSA, CoreMIDI etc. Saw one guy who did a fork of RtMidi to do it, but it's not a part of RtMidi.

**Comment by drewish** [comment]
ah yeah, well it should be possible to fork this module then and swap in that code... i'm just not sure how much effort it'd take.

**Comment by justinlatimer** [comment]
Or try and get the changes from the fork of RtMidi upstream!
