### ISSUE TITLE
How to catch errors?!

### ISSUE THREAD

**Issue by j-waechter** [justinlatimer/node-midi#97]
Hello,

am I overlooking something or is there no way to catch errors?

I have a keyboard whose input can only be opened once. If another application opened it, the console shows this error:

```
MidiInWinMM::openPort: error creating Windows MM MIDI input port.
```

I tried...
- surrounding `input.openPort(...)` with `try { ... } catch (error) { ... }`
- and `input.on('error', function() { ... })` before `input.openPort(...)`

Both variants don't allow me to take control over the error.

_How is one supposed to catch an error like the above?!_

**Comment by julian-weinert** [comment]
:+1:

**Comment by silps** [comment]
Looking also for a solution, looks like the errors are not passed trough the javascript wrapper and just make the process crash.

**Comment by terax111** [comment]
this still isn't properly resolved? there is still no way to catch an error. All it currently does, is keeping the software running. I went ahead and added a Pullrequest to change that
